name: two_hearts
description: "A private digital world for two"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.6
  http: ^1.2.0
  firebase_messaging: ^15.2.5

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.0
  lottie: ^3.3.1

  # Media
  image_picker: ^1.1.2

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  permission_handler: ^11.4.0
  timeago: ^3.7.0

  # 3D / model viewer
  model_viewer_plus: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/models/
