// Generated by FlutterFire CLI.
// Run: flutterfire configure
// Then replace this file with the generated one.
//
// Until then, Firebase.initializeApp() will use google-services.json on Android.
// Place your google-services.json in android/app/ before building.
